Feature/mkk 17 create route employee
kendrickcarrolldc/MAERK pull request #9
Opened 2016-10-31 20:40 UTC by kendrickcarrolldc

Created table for employee app with mock information and ui-view.

2016-10-31 21:11 UTC, anishrijal commented
its ok but u should work on the nav bar, coz when you are logged in u still have login button instead of logout

2016-10-31 22:16 UTC, lchapoy requested changes

2016-10-31 22:16 UTC, lchapoy commented on client/app/main/main.js
>        template: '<main class="flex layout column"></main>'
Change this route to be abstact.
 If main route is not abstract you will have an error when reloading

2016-11-01 19:27 UTC, lchapoy commented on client/app/main/main.js
> +    })
abstract: truegi??? what is that

2016-11-01 19:27 UTC, lchapoy commented on client/app/account/account.js
> +      })
Erase thing that you are not using

2016-11-01 19:27 UTC, lchapoy approved these changes

2016-11-01 19:27 UTC, merged